config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :events
  get 'sessions/new'
  ##get 'sessions/ne'
  get 'users/new'
  get 'admin_users/new'
  get 'managements/index'
  ##get 'pages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/help'

  get 'usergamen', to: 'users#usergamen'

  get 'usershow', to: 'users#usershow'

  ##get '/userlogin', to: 'pages/user'

  ###user 'pages/user'

  #resources :managements
  resources :users

  resources :events

  #resources :users, only: %i(new create) do
  #  collection do
  #    post :new, path: :new, as: :new, action: :back
  #    post :confirm
  #  end
  #end
  
  post  '/users/confirm', to: 'users#confirm'

  ##post  '/users',     to: 'pages/users'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
end

app/models/bk_user.rb
class User < ApplicationRecord
    validates :username, presence: true ,uniqueness: true, length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    #validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :email2, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    #validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

    


end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/fee_howto.rb
class FeeHowto < ApplicationRecord
end

app/models/lesson_style.rb
class LessonStyle < ApplicationRecord
end

app/models/level_kakutei.rb
class LevelKakutei < ApplicationRecord
end

app/models/level_kibou.rb
class LevelKibou < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/models/pinano_history.rb
class PinanoHistory < ApplicationRecord
end

app/models/pinano_owned.rb
class PinanoOwned < ApplicationRecord
end

app/models/user copy 2.rb
class User < ApplicationRecord
    validates :username, presence: true ,uniqueness: true, length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    #validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :email2, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    #validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

    


end

app/models/user copy.rb
class User < ApplicationRecord
    validates :username, presence: true ,uniqueness: true, length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    #validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

    


end

app/models/user.1.rb
class User < ApplicationRecord
end

app/models/user.2.rb
class User < ApplicationRecord
    validates :username, presence: true
    validates :email, presence: true
end

app/models/user.3.rb
class User < ApplicationRecord
    validates :username, presence: true ,length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    #validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

end

app/models/user.4.rb
class User < ApplicationRecord
    validates :username, presence: true ,uniqueness: true, length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    #validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

end

app/models/user.rb
class User < ApplicationRecord

    validates :username, presence: true ,uniqueness: true, length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    validates :age, numericality: true ,length: { minimum:1, maximum: 2 }
    
    
    #validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :email2, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    #validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

    


end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
    ###@yoyakudates=[1,8,22,29] 
    require "date"

    d = Date.today
    while d.wday != 2 do
      d += 1
    end

    @yoyaku = []
    for i in 0..7 do
      ##@yoyaku[i] = {'name' => d.strftime("%Y年 %m月 %d日"), "value" => d.strftime("%Y-%m-%d")}
      ###@yoyaku[i] = {:name => d.strftime("%Y年 %m月 %d日"), :value => d.strftime("%Y-%m-%d")}
      @yoyaku[i] = [d.strftime("%Y年 %m月 %d日"), d.strftime("%Y-%m-%d")]
      ##@yoyaku[i] = d.strftime("%d")

      d += 7

    end
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.users_id=current_user.id

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :description, :start_time, :end_time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/meetings/_form.html copy.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.select( :start_date, @yoyaku) %>
    <%= form.time_select :start_time,
                minute_step:30
        
        
    %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html copy.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.description %></td>
        <td><%= meeting.start_time %></td>
        <td><%= meeting.end_time %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.description %></td>
        <td><%= meeting.start_time.strftime("%Y年%m月%d日") %></td>
        <td><%= meeting.end_time %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

<%= link_to 'Back_UserGamen', usergamen_path %>

app/views/meetings/new.html copy.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/new.html.erb
<div class="u_users-new-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-3 col-md-7 u_users-new-container">
                <h1>予約画面</h1>
                <div class="form-group">
                    <%= render 'form', meeting: @meeting ,class: 'form-control' %>
                </div>
                <%= link_to 'Back', meetings_path %>
                <%= link_to 'Back_UserGamen', usergamen_path %>
            </div>
        </div>

    </div>
</div>

app/views/meetings/show.html copy.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meeting.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meeting.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>