config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :events
  get 'sessions/new'
  ##get 'sessions/ne'
  get 'users/new'
  get 'admin_users/new'
  get 'managements/index'
  ##get 'pages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/help'

  get 'usergamen', to: 'users#usergamen'

  get 'usershow', to: 'users#usershow'

  ##get '/userlogin', to: 'pages/user'

  ###user 'pages/user'

  #resources :managements
  resources :users

  resources :events

  #resources :users, only: %i(new create) do
  #  collection do
  #    post :new, path: :new, as: :new, action: :back
  #    post :confirm
  #  end
  #end
  
  post  '/users/confirm', to: 'users#confirm'

  ##post  '/users',     to: 'pages/users'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
end

app/models/bk_user.rb
class User < ApplicationRecord
    validates :username, presence: true ,uniqueness: true, length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    #validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :email2, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    #validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

    


end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/fee_howto.rb
class FeeHowto < ApplicationRecord
end

app/models/lesson_style.rb
class LessonStyle < ApplicationRecord
end

app/models/level_kakutei.rb
class LevelKakutei < ApplicationRecord
end

app/models/level_kibou.rb
class LevelKibou < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/models/pinano_history.rb
class PinanoHistory < ApplicationRecord
end

app/models/pinano_owned.rb
class PinanoOwned < ApplicationRecord
end

app/models/user copy 2.rb
class User < ApplicationRecord
    validates :username, presence: true ,uniqueness: true, length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    #validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :email2, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    #validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

    


end

app/models/user copy.rb
class User < ApplicationRecord
    validates :username, presence: true ,uniqueness: true, length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    #validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

    


end

app/models/user.1.rb
class User < ApplicationRecord
end

app/models/user.2.rb
class User < ApplicationRecord
    validates :username, presence: true
    validates :email, presence: true
end

app/models/user.3.rb
class User < ApplicationRecord
    validates :username, presence: true ,length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    #validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

end

app/models/user.4.rb
class User < ApplicationRecord
    validates :username, presence: true ,uniqueness: true, length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    #validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

end

app/models/user.rb
class User < ApplicationRecord

    validates :username, presence: true ,uniqueness: true, length: { minimum:2, maximum: 15 },
            format: { 
                with: /\A[a-z0-9]+\z/i , 
                message: "半角英数字のみで入力して下さい"
            }

    validates :age, numericality: true ,length: { minimum:1, maximum: 2 }
    
    
    #validates :email, presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :email2, presence: true, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    validates :password, presence: true, length: { minimum: 8 ,maximum: 32}
    #validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

    


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    require 'date'

    @user = User.new
    @user.lesson_kaisu = 0
    @user.join_date = Date.today
    @user.lesson_nobekaisu = 0
    @user.firstname = '太郎'
    @user.lastname = '漢字'
    @user.kanji_name = '漢字　太郎'
    @user.name_kana = 'カンジ　タロウ'
    @user.email = 'vmak8160@gmail.com'
    @user.email2 = 'ha_arcadia66@yahoo.co.jp'
    @user.age = '15'
    @user.address = '名古屋市中区栄三丁目１１番地'
    @user.zip_code = '460-0008'
    @user.mobile_phone = '090-1234-5689'
    @user.emagency_phone = '080-1234-7890'
    @user.emagency_name = '漢字　総一郎'
    @user.emagency_kana = 'カンジ　ソウイチロウ'
    @user.emagency_zokugara = '祖父'
    

  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
    
  end

  def confirm
    #  確認画面作る
    @user = User.new(user_params)

    if @user.valid?
      @password=user_params[:password]
      render :confirm
    else
      flash.now[:danger] = "入力に不備があります。登録に失敗しました"
      render :new
    end
    
  end

  def usergamen
    @meetings = Meeting.where(users_id: current_user.id)
  end

  def usershow 
    @user = User.where(users_id: current_user.id)
  end

  private
  ##def user_params
  ##  params.require(:user).permit(:username, :email)
  ##end
  def user_params
    ##params.require(:user).permit(:username, :email, :password, :password_confirmation)
    params.require(:user).permit(:username, :email, :address, :lesson_styles_id,
                                 :level_kibous_id, :level_kakuteis_id, :fee_howtos_id, :pinano_owned_id, :pinano_histories_id,
                                 :kanji_name, :name_kana, :firstname, :lastname, :email2, :age, :zip_code, 
                                 :mobile_phone, :emagency_phone, :emagency_name, :emagency_kana, 
                                 :emagency_zokugara, :lesson_kaisu, :lesson_nobekaisu, :join_date,
                                 :password, :password_confirmation)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm.html.erb
<%= asset_path('selectbox.json') %>

<div class="u_users-new-wrapper">
  <div class="container">
  
    <div class="row">
      <div class="col-md-offset-4 col-md-4 u_users-new-container">
        <h1 class="text-center u_text-white">Sign up confrim</h1>
        <%= form_for :user, url: users_path do |f| %>

          <div class="form-group">
            <%= f.label :"ユーザ名(username)", class: 'u_text-white' %>
            <%= f.text_field :username, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"漢字氏名(kanji_name)", class: 'u_text-white' %>
            <%= f.text_field :kanji_name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"氏名かな(name_kana)", class: 'u_text-white' %>
            <%= f.text_field :name_kana, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"名前(firstname)", class: 'u_text-white' %>
            <%= f.text_field :firstname, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"名字(lastname)", class: 'u_text-white' %>
            <%= f.text_field :lastname, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"メールアドレス(email)", class: 'u_text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"メールアドレス同報(email2)", class: 'u_text-white' %>
            <%= f.text_field :email2, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"年齢(age)", class: 'u_text-white' %>
            <%= f.text_field :age, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :"住所(address)", class: 'u_text-white' %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"郵便番号(zip_code)", class: 'u_text-white' %>
            <%= f.text_field :zip_code, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"携帯電話(mobile_phone)", class: 'u_text-white' %>
            <%= f.text_field :mobile_phone, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"緊急連絡先(emagency_phone)", class: 'u_text-white' %>
            <%= f.text_field :emagency_phone, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"緊急連絡先氏名(emagency_name)", class: 'u_text-white' %>
            <%= f.text_field :emagency_name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"緊急連絡先氏名 カナ(emagency_kana)", class: 'u_text-white' %>
            <%= f.text_field :emagency_kana, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"緊急連絡先続柄(emagency_zokugara)", class: 'u_text-white' %>
            <%= f.text_field :emagency_zokugara, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"レッスン回数(lesson_kaisu)", class: 'u_text-white' %>
            <%= f.text_field :lesson_kaisu, value: @user.lesson_kaisu, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"レッスン述べ回数(lesson_nobekaisu)", class: 'u_text-white' %>
            <%= f.text_field :lesson_nobekaisu, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"レベル希望(level_kibou)", class: 'u_text-white' %>
            <%= f.collection_select( :level_kibous_id, LevelKibou.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>
            </div>

          <div class="form-group">
            <%= f.label :"レベル確定(level_kakutei)", class: 'u_text-white' %>
            <%= f.collection_select( :level_kakuteis_id, LevelKakutei.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>
          </div>

          <div class="form-group">
            <%= f.label :"レッスンスタイル(lesson_styles_id)", class: 'u_text-white' %>
            <%= f.collection_select( :lesson_styles_id, LessonStyle.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>
          </div>

          <div class="form-group">
            <%= f.label :"支払い方法(fee_howto)", class: 'u_text-white' %>
            <%= f.collection_select( :fee_howtos_id, FeeHowto.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>
          </div>

          <div class="form-group">
            <%= f.label :"ピアノ有無(pinano_owned)", class: 'u_text-white' %>
            <%= f.collection_select( :pinano_owned_id, PinanoOwned.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>

          <div class="form-group">
            <%= f.label :"ピアノ歴(pinano_history)", class: 'u_text-white' %>
            <%= f.collection_select( :pinano_histories_id, PinanoHistory.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>
          </div>

          <div class="form-group">
            <%= f.label :"入会日(join_date)", class: 'u_text-white' %>
            <%= f.text_field :join_date, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :"パスワード(password)", class: 'u_text-white' %>
            <%= f.text_field :password, class: 'form-control' ,value: @password %>
          </div>

          <div class="form-group">
            <%= f.label :"パスワード再確認(password_confirmation)", class: 'u_text-white' %>
            <%= f.text_field :password_confirmation, class: 'form-control'  %>
          </div>

 
          <%= f.submit "ユーザ登録", class: 'btn-block u_btn-white' %>

          
        <% end %>
        <%= link_to 'ログインはこちら', login_path,class: 'u_text-white' %>
      </div>
    </div>



  </div>
</div>

app/views/users/new.html copy 10.erb
<%= asset_path('selectbox.json') %>

<div class="u_users-new-wrapper">
  <div class="container">
  
    <div class="row">
      <div class="col-md-offset-4 col-md-4 u_users-new-container">
        <h1 class="text-center u_text-white">Sign up</h1>
        <%= form_for :user, url: confirm_users_path do |f| %>

          <div class="form-group">
            <%= f.label :"ユーザ名(username)", class: 'u_text-white' %>
            <%= f.text_field :username, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"漢字氏名(kanji_name)", class: 'u_text-white' %>
            <%= f.text_field :kanji_name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"氏名かな(name_kana)", class: 'u_text-white' %>
            <%= f.text_field :name_kana, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"名前(firstname)", class: 'u_text-white' %>
            <%= f.text_field :firstname, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"名字(lastname)", class: 'u_text-white' %>
            <%= f.text_field :lastname, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"メールアドレス(email)", class: 'u_text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"メールアドレス同報(email2)", class: 'u_text-white' %>
            <%= f.text_field :email2, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"年齢(age)", class: 'u_text-white' %>
            <%= f.text_field :age, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :"住所(address)", class: 'u_text-white' %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"郵便番号(zip_code)", class: 'u_text-white' %>
            <%= f.text_field :zip_code, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"携帯電話(mobile_phone)", class: 'u_text-white' %>
            <%= f.text_field :mobile_phone, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"緊急連絡先(emagency_phone)", class: 'u_text-white' %>
            <%= f.text_field :emagency_phone, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"緊急連絡先氏名(emagency_name)", class: 'u_text-white' %>
            <%= f.text_field :emagency_name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"緊急連絡先氏名 カナ(emagency_kana)", class: 'u_text-white' %>
            <%= f.text_field :emagency_kana, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"緊急連絡先続柄(emagency_zokugara)", class: 'u_text-white' %>
            <%= f.text_field :emagency_zokugara, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"レッスン回数(lesson_kaisu)", class: 'u_text-white' %>
            <%= f.text_field :lesson_kaisu, value: @user.lesson_kaisu, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"レッスン述べ回数(lesson_nobekaisu)", class: 'u_text-white' %>
            <%= f.text_field :lesson_nobekaisu, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"レベル希望(level_kibou)", class: 'u_text-white' %>
            <%= f.collection_select( :level_kibous_id, LevelKibou.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>
            </div>

          <div class="form-group">
            <%= f.label :"レベル確定(level_kakutei)", class: 'u_text-white' %>
            <%= f.collection_select( :level_kakuteis_id, LevelKakutei.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>
          </div>

          <div class="form-group">
            <%= f.label :"レッスンスタイル(lesson_styles_id)", class: 'u_text-white' %>
            <%= f.collection_select( :lesson_styles_id, LessonStyle.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>
          </div>

          <div class="form-group">
            <%= f.label :"支払い方法(fee_howto)", class: 'u_text-white' %>
            <%= f.collection_select( :fee_howtos_id, FeeHowto.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>
          </div>

          <div class="form-group">
            <%= f.label :"ピアノ有無(pinano_owned)", class: 'u_text-white' %>
            <%= f.collection_select( :pinano_owned_id, PinanoOwned.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>

          <div class="form-group">
            <%= f.label :"ピアノ歴(pinano_history)", class: 'u_text-white' %>
            <%= f.collection_select( :pinano_histories_id, PinanoHistory.all, :id, :name, {prompt:  "選択してください"}, {class: "form-control input-sm"}) %>
          </div>

          <div class="form-group">
            <%= f.label :"入会日(join_date)", class: 'u_text-white' %>
            <%= f.text_field :join_date, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :"パスワード(password)", class: 'u_text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"パスワード再確認(password_confirmation)", class: 'u_text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

 
          <%= f.submit "確認画面へ", class: 'btn-block u_btn-white' %>

          
        <% end %>
        <%= link_to 'ログインはこちら', login_path,class: 'u_text-white' %>
      </div>
    </div>



  </div>
</div>

app/views/users/new.html copy 2.erb
<%= asset_path('selectbox.json') %>

<div class="u_users-new-wrapper">
  <div class="container">
  
    <div class="row">
      <div class="col-md-offset-4 col-md-4 u_users-new-container">
        <h1 class="text-center u_text-white">Sign up</h1>
        <%= form_for @user do |f| %>

          <div class="form-group">
            <%= f.label :"ユーザ名(username)", class: 'u_text-white' %>
            <%= f.text_field :username, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :"漢字氏名(kanji_name)", class: 'u_text-white' %>
            <%= f.text_field :kanji_name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :firstname, class: 'u_text-white' %>
            <%= f.text_field :firstname, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :lastname, class: 'u_text-white' %>
            <%= f.text_field :lastname, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, class: 'u_text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email2, class: 'u_text-white' %>
            <%= f.text_field :email2, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :age, class: 'u_text-white' %>
            <%= f.text_field :age, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :"住所(address)", class: 'u_text-white' %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :zip_code, class: 'u_text-white' %>
            <%= f.text_field :zip_code, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :mobile_phone, class: 'u_text-white' %>
            <%= f.text_field :mobile_phone, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :emagency_phone, class: 'u_text-white' %>
            <%= f.text_field :emagency_phone, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :emagency_zokugara, class: 'u_text-white' %>
            <%= f.text_field :emagency_zokugara, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :lesson_kaisu, class: 'u_text-white' %>
            <%= f.text_field :lesson_kaisu, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :lesson_nobekaisu, class: 'u_text-white' %>
            <%= f.text_field :lesson_nobekaisu, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :level_kibou, class: 'u_text-white' %>
            <%= f.text_field :level_kibou, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :level_kakutei, class: 'u_text-white' %>
            <%= f.text_field :level_kakutei, class: 'form-control' %>
          </div>


      
          <div class="form-group">
            <%= f.label :lesson_style, class: 'u_text-white' %>
            <%= f.collection_select :lesson_style, LessonStyle.all, :id, :name, :prompt => "選択してください" , class: 'form-control' %>
          </div>


          <div class="form-group">
            <%= f.label :fee_howto, class: 'u_text-white' %>
            <%= f.text_field :fee_howto, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :pinano_owned, class: 'u_text-white' %>
            <%= f.text_field :pinano_owned, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :pinano_history, class: 'u_text-white' %>
            <%= f.text_field :pinano_history, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :join_date, class: 'u_text-white' %>
            <%= f.text_field :join_date, class: 'form-control' %>
          </div>
    
          <div class="form-group">
            <%= f.label :password, class: 'u_text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, class: 'u_text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

 

          <%= f.submit "登録", class: 'btn-block u_btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path,class: 'u_text-white' %>
      </div>
    </div>



  </div>
</div>

app/views/users/usergamen.html copy 3.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Piano Lesson</h1>
    <h2 class="text-white">Special music salon 会員様専用ページ</h2>
    <div class="row">

      <div class="col-md-offset-1 col-md-3">
        <%= link_to '支払い', new_user_path, class: 'btn btn-block btn-white' %>
      </div>

      <div class="col-md-offset-1 col-md-3">
        <%#= link_to '予約登録', login_path,class: 'btn btn-block btn-white' %>
        <%= link_to '予約登録', meetings_path,class: 'btn btn-block btn-white' %>
      </div>

      <div class="col-md-offset-1 col-md-3">
        <%= link_to '登録情報確認', login_path,class: 'btn btn-block btn-white' %>
      </div>

    </div>
    
    <div class="row">


      <%= month_calendar events: @meetings do |date, meetings| %>
       <%# d = Date.parse(date) %>
       <%= date.strftime("%d") %>
    
       <% meetings.each do |meeting| %>
         <div>
           <%= link_to meeting.name, meeting %>
           <%#= meeting.name %>
         </div>
       <% end %>
     <% end %>
    </div>


  </div>

 
   
  

</div>

app/views/users/usergamen.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Piano Lesson</h1>
    <h2 class="text-white">Special music salon 会員様専用ページ</h2>
    <div class="row">

      <div class="col-md-offset-1 col-md-3">
        <%= link_to '支払い', new_user_path, class: 'btn btn-block btn-white' %>
      </div>

      <div class="col-md-offset-1 col-md-3">
        <%#= link_to '予約登録', login_path,class: 'btn btn-block btn-white' %>
        <%= link_to '予約登録', meetings_path,class: 'btn btn-block btn-white' %>
      </div>

      <div class="col-md-offset-1 col-md-3">
        <%= link_to '登録情報確認', usershow_path,class: 'btn btn-block btn-white' %>
      </div>

    </div>
    
    <div class="row">


      <%= month_calendar events: @meetings do |date, meetings| %>
       <%# d = Date.parse(date) %>
       <%= date.strftime("%d") %>
    
       <% meetings.each do |meeting| %>
         <div>
           <%= link_to meeting.name, meeting %>
           <%#= meeting.name %>
         </div>
       <% end %>
     <% end %>
    </div>


  </div>

 
   
  

</div>